# Generated by Django 4.1.1 on 2023-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenominee',
            name='photo',
            field=models.ImageField(upload_to='votingapp/static/nomineephotos'),
        ),
    ]
